### ISSUE TITLE
Validate Backtesting Period

### ISSUE THREAD

**Issue by marijn111** [dema-trading-ai/engine#240]
The following (erroneous) backtesting period caused an error:

```
  "backtesting-from": "2021-04-9",    # Should be 09
  "backtesting-to": "2021-04-24",
  "backtesting-till-now": false,
```

Trace:

```
====================================== 
Starting up DEMA BACKTESTING 
======================================
[INFO] The algorithm will use the inputted value of 0.25% as fee percentage.
[INFO] Configuring timeframe...
[INFO] Connecting to exchange...
[INFO] Connected to exchange: binance.
Traceback (most recent call last):
  File "/usr/src/engine/main.py", line 25, in <module>
    main()
  File "/usr/src/engine/main.py", line 8, in main
    execute_for_args({
  File "/usr/src/engine/cli/arg_parse.py", line 39, in execute_for_args
    args.func(args)
  File "/usr/src/engine/main.py", line 16, in run_engine
    controller = MainController(args)
  File "/usr/src/engine/main_controller.py", line 14, in __init__
    self.config = ConfigModule(args)
  File "/usr/src/engine/modules/setup/config/__init__.py", line 45, in __init__
    self.backtesting_from, self.backtesting_to = config_from_to(self.exchange, backtesting_from, backtesting_to,
  File "/usr/src/engine/modules/setup/config/__init__.py", line 122, in config_from_to
    if backtesting_from >= backtesting_to:
  TypeError: '>=' not supported between instances of 'NoneType' and 'int'
```

Backtesting period should be validated and the user should be notified accordingly.

**Comment by sheridavandenbent** [comment]
Gives a proper error message now.
